maui-toolkit/Calendar/getting-started.md

Description:
Made Corrections on Calendar UG for Toolkit Repository

924195-Update-Calendar-UG

---

maui-toolkit/Migration.md

Description:
Adding Missing Calendar Changes

924195-Add Missing Changes for Calendar 

---

maui-toolkit/Bottom-Sheet/BottomSheet-Content.md
maui-toolkit/Bottom-Sheet/Getting-Started.md
maui-toolkit/Bottom-Sheet/Swipe-Gesture.md
maui-toolkit/Bottom-Sheet/Toggling-Sheet.md

Updated the examples in .Net maui Bottom Sheet

Updated the examples in .Net Maui Bottom Sheet

---

maui-toolkit/Button/how-to/Add-the-custom-view-for-button.md

Revamped toolkit button UG

---

maui-toolkit/Button/Customization.md

Added BackgroundImageAspect property content

Added Title for BackgroundImageAspect for Toolkit Button

---

maui-toolkit/Bottom-Sheet/BottomSheet-Content.md
maui-toolkit/Bottom-Sheet/BottomSheet-Customization.md
maui-toolkit/Bottom-Sheet/Getting-Started.md

Update the Content for BottomSheet.

Update the Content for BottomSheet.

---

maui-toolkit/Bottom-Sheet/Getting-Started.md
maui-toolkit/Effects-View/Getting-Started.md
maui-toolkit/NavigationDrawer/Getting-Started.md
maui-toolkit/TabView/Getting-Started.md

Added tabcontent tag.

---

maui-toolkit/Bottom-Sheet/BottomSheet-Content.md
maui-toolkit/Bottom-Sheet/BottomSheet-Customization.md
maui-toolkit/Bottom-Sheet/Events.md
maui-toolkit/Bottom-Sheet/Getting-Started.md
maui-toolkit/Bottom-Sheet/Swipe-Gesture.md
maui-toolkit/Bottom-Sheet/Toggling-Sheet.md

- Added API links for Bottom Sheet.

Added API links for Bottom Sheet.

---

maui-toolkit/TabView/Nested-Tabs.md

- Added Enable Virtualization content for tab view.

Added Enable Virtualization content for tab view.

---

maui-toolkit/Calendar/getting-started.md
maui-toolkit/Migration.md

Description:
Made Corrections On UG

924195-Made-Corrections on UG

---

maui-toolkit/Calendar/getting-started.md
maui-toolkit/Migration.md

Description:
Made Corrections on the Name Spaces

924195-Made Correction on Name Space

---

maui-toolkit/TabView/Selection-Indicator-Customization.md
maui-toolkit/TabView/Tab-Item-Customization.md

- Added API links for TabView.

Added API link for tabview features.

---

maui-toolkit/TabView/Selection-Indicator-Customization.md
maui-toolkit/TabView/Tab-Item-Customization.md

- Added API links for TabView.

Added API links for TabView.

---

maui-toolkit/Cards/getting-started.md

**Description**
Update cards visual studio version.

Update Cards Visual Studio Version

---

maui-toolkit/Calendar/getting-started.md
maui-toolkit/Cards/getting-started.md
maui-toolkit/Segmented-Control/getting-started.md
maui-toolkit/Shimmer/getting-started.md

Hi @MuniappanSubramanian,
Getting Started UG document updated for the below controls.
- Calendar
- Shimmer
- Segment
- Cards
Regards,
Indumathi R

MAUI-914189-ToolkitUGUpdation-Getting started UG updated.

---

maui-toolkit/Cartesian-Charts/Getting-Started.md
maui-toolkit/Circular-Charts/Getting-Started.md
maui-toolkit/Funnel-Charts/Getting-Started.md
maui-toolkit/Polar-Charts/Getting-Started.md
maui-toolkit/Pyramid-Charts/Getting-Started.md

Updated the Toolkit package project creation and installation section with tabs in the Getting-Started.md files for the chart controls.

Update Charts Getting Started

---

maui-toolkit/Popup/getting-started.md

- Adding Taps to the VS and VS Code for full toolkit popup

Adding Taps to the VS and VS Code for full toolkit popup

---

maui-toolkit/Cartesian-Charts/Getting-Started.md
maui-toolkit/Circular-Charts/Getting-Started.md
maui-toolkit/Funnel-Charts/Getting-Started.md
maui-toolkit/Polar-Charts/Getting-Started.md
maui-toolkit/Pyramid-Charts/Getting-Started.md

Updated tab content in gettingstarted.md files for chart controls.
Reference PR https://github.com/syncfusion-content/maui-toolkit-docs/pull/199

Update Tab Content for Charts Getting Started

---

maui-toolkit/Pull-to-Refresh/getting-started.md

Changed to individual tab for pull to refresh

Changed to individual tabs

---

maui-toolkit-toc.html

**Description**
- Reverting TOC file for Expander, Accordion, Cards, & Popup

Reverting TOC file for Expander, Accordion , Cards, & Popup

---

maui-toolkit-toc.html

**Description**
- Reverting TOC file for Expander, Accordion, Cards, & Popup

Reverting TOC file for Expander, Accordion, Cards, & Popup

---

maui-toolkit/Accordion/getting-started.md
maui-toolkit/Bottom-Sheet/Getting-Started.md
maui-toolkit/Button/Getting-Started.md
maui-toolkit/Calendar/getting-started.md
maui-toolkit/Cards/getting-started.md
maui-toolkit/Carousel-View/Getting-Started.md
maui-toolkit/Cartesian-Charts/Getting-Started.md
maui-toolkit/Chips/Getting-Started.md
maui-toolkit/Circular-Charts/Getting-Started.md
maui-toolkit/Effects-View/Getting-Started.md
maui-toolkit/Expander/getting-started.md
maui-toolkit/Funnel-Charts/Getting-Started.md
maui-toolkit/NavigationDrawer/Getting-Started.md
maui-toolkit/NumericEntry/Getting-Started.md
maui-toolkit/NumericUpDown/Getting-Started.md
maui-toolkit/Polar-Charts/Getting-Started.md
maui-toolkit/Popup/getting-started.md
maui-toolkit/Pull-to-Refresh/getting-started.md
maui-toolkit/Pyramid-Charts/Getting-Started.md
maui-toolkit/Segmented-Control/getting-started.md
maui-toolkit/Shimmer/getting-started.md
maui-toolkit/TabView/Getting-Started.md
maui-toolkit/TextInputLayout/Getting-Started.md

**Added Jedbrains Rider for toolkit controls**

936815: Added JetBrains Rider documentation in the Maui controls getting started page 

---

maui-toolkit/Themes/HowTo.md

**Description:**
Updated the Maui Toolkit UG-example for Themes/HowTo.md
Ticket: https://support.syncfusion.com/agent/tickets/689808

Ticket-689808: Updated the Maui Toolkit UG-example for Themes/HowTo.md

---

maui-toolkit/Chips/Getting-Started.md

Hi Teasm,
I've Update chip Documentation regarding AOT details during publish on IOS.

942946 - Update chip Documentation regarding AOT details.

---

maui-toolkit/Migration.md

Added Accordion and Expander control in migration page.

Added Accordion and Expander control in migration page.

---

maui-toolkit/Otp-Input/Input-Types.md

Updated the API reference for Type Property

Updated the API reference

---

maui-toolkit/Themes/Keys.md

Added theme keys for OtpInput and BottomSheet controls

943738 Added theme keys for OtpInput and BottomSheet controls - Master

---

maui-toolkit/Accordion/appearance.md
maui-toolkit/Accordion/bindablelayout.md
maui-toolkit/Accordion/events.md
maui-toolkit/Accordion/getting-started.md
maui-toolkit/Expander/appearance.md
maui-toolkit/Expander/getting-started.md

Added API links for Accordion and Expander control.

Added API links for Accordion and Expander control.

---

maui-toolkit/Popup/Popup-Events.md
maui-toolkit/Popup/getting-started.md
maui-toolkit/Popup/layout-customizations.md
maui-toolkit/Popup/modal-window.md
maui-toolkit/Popup/popup-animations.md
maui-toolkit/Popup/popup-positioning.md
maui-toolkit/Popup/popup-size.md
maui-toolkit/Popup/styles.md
maui-toolkit/Popup/working-with-mvvm.md

Included API reference for the public API's for MAUI Toolkit Popup

Included API reference for the public API's for MAUI Toolkit Popup

---

maui-toolkit/Popup/popup-positioning.md

**Description:**
- Updating popup-positioning.md file

Updating popup-positioning.md file

---

maui-toolkit/Calendar/getting-started.md
maui-toolkit/Calendar/localization.md
maui-toolkit/Cards/getting-started.md

Description:
Fixed Spelling Mistake
Task ID:
https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/955646/

955646-Fixed-Spelling-Mistake[Hotfix]

---

maui-toolkit/Calendar/getting-started.md
maui-toolkit/Calendar/localization.md
maui-toolkit/Cards/getting-started.md
maui-toolkit/CircularProgressBar/getting-started.md
maui-toolkit/LinearProgressBar/getting-started.md

Description:
Made Corrections on Spelling Mistake.

955646- Fixed Spelling Mistake

---

maui-toolkit/Calendar/getting-started.md

Cleared Conflicts
Task : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/957174/

957174-Clear-Conflicts

---

maui-toolkit-toc.html
maui-toolkit/Release-notes/v1.0.5.md

MAUI ToolKit Release 1.0.5 changes added

MAUI ToolKit Release 1.0.5 changes added

---

maui-toolkit/Installation.md
maui-toolkit/Introduction/Overview.md
maui-toolkit/Migration.md
maui-toolkit/Themes/HowTo.md
maui-toolkit/Themes/Keys.md
maui-toolkit/Themes/Themes.md

Reviewed UG content for:
- [Overview](https://help.syncfusion.com/maui-toolkit/introduction/overview)
- [Installation](https://help.syncfusion.com/maui-toolkit/installation)
- [Themes](https://help.syncfusion.com/maui-toolkit/themes/themes)
- [Migration](https://help.syncfusion.com/maui-toolkit/migration)

Reviewed the UG content for the common files

---

maui-toolkit/Themes/Keys.md

Updated the rowspan count for OtpInput keys table

965989 - Updated the rowspan count for OtpInput keys table

---

maui-toolkit/Otp-Input/OtpInput-Customization.md

Added Ug Content for BoxWidth and BoxHeight properties

Added Ug Content for BoxWidth and BoxHeight properties

---

maui-toolkit-toc.html
maui-toolkit/Segmented-Control/customization.md
maui-toolkit/Segmented-Control/events.md
maui-toolkit/Segmented-Control/selection.md

979465-Updated content for the ug documentation of segmented control features

979465-Updated content for the ug documentation of segmented control features
